# Generated by Django 4.1 on 2022-11-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('eid', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('doj', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_place', models.CharField(default=True, max_length=50, null=True)),
                ('father_name', models.CharField(default=True, max_length=50, null=True)),
                ('mother_name', models.CharField(default=True, max_length=50, null=True)),
                ('dob', models.DateField(default=True, null=True)),
                ('address', models.CharField(default=True, max_length=50, null=True)),
                ('aadhar', models.IntegerField(default=True, null=True)),
                ('ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Educational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_percentage', models.IntegerField(default=True, null=True)),
                ('inter_percentage', models.IntegerField(default=True, null=True)),
                ('degree_percentage', models.IntegerField(default=True, null=True)),
                ('ssc_passoutyear', models.DateField(default=True, null=True)),
                ('inter_passoutyear', models.DateField(default=True, null=True)),
                ('degree_passoutyear', models.DateField(default=True, null=True)),
                ('ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
