# Generated by Django 4.1 on 2022-11-24 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('bus_name', models.CharField(max_length=200)),
                ('vehicle_num', models.CharField(max_length=200)),
                ('driver_no', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('destination_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.destination')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='busdetails',
            name='destination_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.destination'),
        ),
    ]
