# Generated by Django 4.1 on 2022-09-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('eid', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.BinaryField()),
                ('description', models.TextField(max_length=30)),
                ('Indian', models.BooleanField()),
                ('c', models.URLField()),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
