# Generated by Django 4.1 on 2022-11-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('joindate', models.DateField()),
                ('sal', models.FloatField()),
                ('loc', models.CharField(max_length=30)),
                ('commi', models.FloatField()),
            ],
        ),
    ]
