# Generated by Django 4.1 on 2022-12-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('eno', models.IntegerField()),
                ('esal', models.CharField(max_length=20)),
                ('add', models.CharField(max_length=20)),
            ],
        ),
    ]
