# Generated by Django 4.1 on 2022-12-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='add',
        ),
    ]
