# Generated by Django 4.1 on 2022-10-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=15)),
                ('cno', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
