# Generated by Django 4.1 on 2022-10-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='host',
            new_name='hostel',
        ),
    ]
