# Generated by Django 4.1 on 2022-12-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('eno', models.IntegerField()),
                ('esal', models.CharField(max_length=20)),
                ('add', models.CharField(max_length=20)),
            ],
        ),
    ]
